window.exportTab = (() => {

    function render() {
        // The HTML content for the export tab is generated by ui_components.js
        // and includes the buttons for triggering various export actions.
        const contentHTML = window.uiComponents.createExportTabContentHTML();
        
        // This tab doesn't have dynamic content that needs to be rendered via D3 or
        // special DOM manipulation after initial load, so a simple return is sufficient.
        // Event listeners are handled by event_manager.js for the buttons within this HTML.
        return contentHTML;
    }

    return Object.freeze({
        render
    });
})();